apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "music-assistant-skill.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "music-assistant-skill.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "music-assistant-skill.name" . }}
    spec:
      containers:
        - name: music-assistant-skill
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.env.PORT }}
            - containerPort: {{ .Values.env.DEBUG_PORT }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            - name: APP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "music-assistant-skill.fullname" . }}
                  key: APP_USERNAME
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "music-assistant-skill.fullname" . }}
                  key: APP_PASSWORD
          volumeMounts:
            - name: ask-data
              mountPath: /root/.ask
      volumes:
        - name: ask-data
          persistentVolumeClaim:
            claimName: {{ include "music-assistant-skill.fullname" . }}-pvc