apiVersion: v1
kind: Service
metadata:
  name: {{ include "music-assistant-skill.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "music-assistant-skill.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.env.PORT }}
    - name: debug
      port: {{ .Values.service.debugPort }}
      targetPort: {{ .Values.env.DEBUG_PORT }}