apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  template:
    metadata:
      name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
          image: "gotenberg/gotenberg:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
              name: gotenberg-port
          resources:
            requests:
              memory: "{{ .Values.gotenberg.resources.requests.memory }}"
              cpu: "{{ .Values.gotenberg.resources.requests.cpu }}"
              ephemeral-storage: "{{ .Values.gotenberg.resources.requests.ephemeralStorage }}"
            limits:
              memory: "{{ .Values.gotenberg.resources.limits.memory }}"
              cpu: "{{ .Values.gotenberg.resources.limits.cpu }}"
              ephemeral-storage: "{{ .Values.gotenberg.resources.limits.ephemeralStorage }}"
      restartPolicy: Always
