apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: gotenberg-port
      name: gb-s-port
  type: ClusterIP
