config:
  storage: 50Gi
  storageClass: longhorn
  secretRef:
    db: null
    zipline: null
  domain: null
  maxUploadFileSize: 30m
zipline:
  resources:
    requests:
      cpu: 0.1
      memory: 265Mi
      ephemeralStorage: 10Mi
    limits:
      cpu: 1
      memory: 768Mi
      ephemeralStorage: 10Mi