image:
  repository: ghcr.io/alams154/music-assistant-skill
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

env:
  SKILL_HOSTNAME: skill.example.com
  MA_HOSTNAME: ""
  PORT: 5000
  DEBUG_PORT: 5678
  LOCALE: en-US
  AWS_DEFAULT_REGION: us-east-1
  TZ: America/Chicago

secrets:
  OnePw: null

service:
  type: ClusterIP
  port: 5000
  debugPort: 5678

persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: skill.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true
    secretName: music-assistant-tls