name: Publish TeamSpeak Server Helm Chart
on:
  workflow_dispatch:
  push:
    paths:
      - teamspeak-server/**
jobs:
  publish-teamspeak-server:
    name: Publish TeamSpeak Server Helm Chart
    uses: ./.github/workflows/publish-helm-chart.yml
    with:
      chart-name: 'teamspeak-server'
    secrets: inherit
  deploy-teamspeak-server:
    name: Deploy TeamSpeak Server Helm Chart
    needs: publish-teamspeak-server
    uses: ./.github/workflows/deploy-helm-chart.yml
    with:
      deployment-identifier: 'teamspeak-server'
      chart-version: ${{ needs.publish-teamspeak-server.outputs.chart-version }}
    secrets: inherit
