name: Publish Apache Tika Helm Chart
on:
  workflow_dispatch:
  push:
    paths:
      - apache-tika/**
jobs:
  publish-apache-tika:
    name: Publish Apache Tika Helm Chart
    uses: ./.github/workflows/publish-helm-chart.yml
    with:
      chart-name: 'apache-tika'
    secrets: inherit
  deploy-cluster-tika:
    name: Deploy Cluster-Tika
    needs: publish-apache-tika
    uses: ./.github/workflows/deploy-helm-chart.yml
    with:
      deployment-identifier: 'cluster-tika'
      chart-version: ${{ needs.publish-apache-tika.outputs.chart-version }}
    secrets: inherit
