name: Publish Calibre Web Automated Helm Chart
on:
  workflow_dispatch:
  push:
    paths:
      - calibre-web-automated/**
jobs:
  publish-calibre-web-automated:
    name: Publish Calibre Web Automated Helm Chart
    uses: ./.github/workflows/publish-helm-chart.yml
    with:
      chart-name: 'calibre-web-automated'
    secrets: inherit
  deploy-calibre-web-automated:
    name: Deploy Calibre Web Automated Helm Chart
    needs: publish-calibre-web-automated
    uses: ./.github/workflows/deploy-helm-chart.yml
    with:
      deployment-identifier: 'calibre-web-automated'
      chart-version: ${{ needs.publish-calibre-web-automated.outputs.chart-version }}
    secrets: inherit
