name: Publish Samba Helm Chart
on:
  workflow_dispatch:
  push:
    paths:
      - samba/**
jobs:
  publish-samba:
    name: Publish Samba Helm Chart
    uses: ./.github/workflows/publish-helm-chart.yml
    with:
      chart-name: 'samba'
    secrets: inherit
  deploy-samba:
    name: Deploy Samba Helm Chart
    needs: publish-samba
    uses: ./.github/workflows/deploy-helm-chart.yml
    with:
      deployment-identifier: 'cluster-smb'
      chart-version: ${{ needs.publish-samba.outputs.chart-version }}
    secrets: inherit
